# REASON: This workflow ensures all Pull Request titles adhere to the Conventional Commits specification.
# This is critical for the "squash merge" strategy into the 'dev' branch.
name: 'Lint PR Title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  statuses: write

jobs:
  lint-pr-title:
    name: 'Check PR Title'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check PR title against Conventional Commits'
        # Using the latest stable version as per the documentation
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A list of valid types, separated by newlines.
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          
          # A list of valid scopes, separated by newlines.
          # We are explicitly listing scopes from our .commitlintrc.json to ensure consistency.
          scopes: |
            project
            activity
            payment
            activity-schema
            payment-schema
            release
            
          # REASON: The subject (the main description) of a commit message should never be empty.
          # This regex ensures there is at least one character in the subject.
          subjectPattern: ".+"
          
          # Optional: Custom error message for the subject pattern.
          subjectPatternError: "The subject of the PR title must not be empty."
          
          # CRITICAL FIX: Enforce the presence of a scope.
          # This parameter makes the scope mandatory, aligning the server-side check
          # with our local commitlint rules. Defaults to 'false' if not specified.
          requireScope: true